### ISSUE TITLE
Side bar buttons/text components not dynamic on screen resize 

### ISSUE THREAD

**Issue by arnavbhola123** [kct417/taskify#18]
![Screenshot 2024-05-14 at 11 59 54 PM](https://github.com/kct417/csc-307-todo-list-app/assets/113968467/88c42383-05e0-4866-9f43-d5503000e4c6)

**Comment by charlescohanlon** [comment]
This isn't a big issue because the prof says the UI doesn't need to be responsive. Fitting on only one kind of screen is fine.
